apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelinetest-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipelinetest-app
  template:
    metadata:
      labels:
        app: pipelinetest-app
    spec:
      containers:
      - name: pipelinetest-app
        image: castlehoo/pipelinetest_image:16
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: dockerhub-secret
